image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Terminal 1
    before: echo 'before script'
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: Terminal 2
    init: npm install
    command: npm run dev
  - name: Start web server
    init: python -m http.server 8000

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - octref.vetur@0.34.1
